// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cat_media.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatMedia = `-- name: CountCatMedia :one
select count(*) from cat_media where cat_id = $1
`

// backs the cover photo's count pill (docs/design/screens/cat-profile.html)
// without fetching the full archive.
func (q *Queries) CountCatMedia(ctx context.Context, catID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCatMedia, catID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCatMedia = `-- name: CreateCatMedia :one
insert into cat_media (cat_id, media_id, created_at)
values ($1, $2, $3)
on conflict (cat_id, media_id) do nothing
returning id, cat_id, media_id, created_at
`

type CreateCatMediaParams struct {
	CatID     pgtype.UUID        `json:"cat_id"`
	MediaID   pgtype.UUID        `json:"media_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// issue #121: links a media row into a cat's photo archive. On conflict do
// nothing on the (cat_id, media_id) unique index so a retried insert of the
// same photo (e.g. CreateCatWithMedia's own transaction, called again after
// an idempotent-retry resolves to the same cat and media) never creates a
// second archive entry — the caller falls back to GetCatMediaByCatAndMedia
// when no row comes back, mirroring CreateMedia/CreateCat's own idempotent
// pattern.
func (q *Queries) CreateCatMedia(ctx context.Context, arg CreateCatMediaParams) (CatMedium, error) {
	row := q.db.QueryRow(ctx, createCatMedia, arg.CatID, arg.MediaID, arg.CreatedAt)
	var i CatMedium
	err := row.Scan(
		&i.ID,
		&i.CatID,
		&i.MediaID,
		&i.CreatedAt,
	)
	return i, err
}

const getCatMediaByCatAndMedia = `-- name: GetCatMediaByCatAndMedia :one
select id, cat_id, media_id, created_at from cat_media where cat_id = $1 and media_id = $2
`

type GetCatMediaByCatAndMediaParams struct {
	CatID   pgtype.UUID `json:"cat_id"`
	MediaID pgtype.UUID `json:"media_id"`
}

func (q *Queries) GetCatMediaByCatAndMedia(ctx context.Context, arg GetCatMediaByCatAndMediaParams) (CatMedium, error) {
	row := q.db.QueryRow(ctx, getCatMediaByCatAndMedia, arg.CatID, arg.MediaID)
	var i CatMedium
	err := row.Scan(
		&i.ID,
		&i.CatID,
		&i.MediaID,
		&i.CreatedAt,
	)
	return i, err
}

const listCatMedia = `-- name: ListCatMedia :many
select
  cm.id,
  cm.cat_id,
  cm.media_id,
  cm.created_at,
  m.url,
  m.content_type,
  m.muted,
  coalesce(c.primary_photo_id = cm.media_id, false) as is_cover,
  uu.display_name as uploader_display_name
from cat_media cm
join media m on m.id = cm.media_id
join cats c on c.id = cm.cat_id
left join users uu on uu.id = m.uploaded_by_user_id
where cm.cat_id = $1
  and (
    not exists (
      select 1 from updates u where u.media_id = cm.media_id and u.cat_id = cm.cat_id
    )
    or exists (
      select 1 from updates u
      where u.media_id = cm.media_id and u.cat_id = cm.cat_id and u.deleted_at is null
    )
  )
order by cm.created_at desc, cm.id desc
`

type ListCatMediaRow struct {
	ID                  pgtype.UUID        `json:"id"`
	CatID               pgtype.UUID        `json:"cat_id"`
	MediaID             pgtype.UUID        `json:"media_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Url                 string             `json:"url"`
	ContentType         string             `json:"content_type"`
	Muted               bool               `json:"muted"`
	IsCover             bool               `json:"is_cover"`
	UploaderDisplayName pgtype.Text        `json:"uploader_display_name"`
}

// backs the "medya" archive tab: newest-first, each row carrying the media
// it points to plus whether it's the cat's current cover (cats.primary_photo_id)
// so the client can render the design's "ana" badge without a second lookup.
// uploader_display_name (issue #154's media-attribution parity gap) mirrors
// ListCatUpdates' own author_display_name: left-joined and nullable because
// a linked account may never have set one (00015), never because the
// uploader is unknown (media.uploaded_by_user_id is not null).
// the where clause's exists/not-exists pair hides media whose only owning
// update has been soft-deleted (deleted update media must vanish from the
// archive same as it vanished from the timeline): a row survives when
// either no update ever attached this media (the cat's own creation photo,
// see Store.CreateCatWithMedia, or a future non-update write path) or at
// least one update still attaching it remains non-deleted. this is a
// read-time filter only — the cat_media row itself is never touched, so
// historical data stays intact for audit/recovery. the cover can never
// reach the "hidden" branch: DeleteOwnUpdate refuses to delete an update
// that owns the cat's current cover, so a live cover's owning update is
// never soft-deleted out from under it.
func (q *Queries) ListCatMedia(ctx context.Context, catID pgtype.UUID) ([]ListCatMediaRow, error) {
	rows, err := q.db.Query(ctx, listCatMedia, catID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatMediaRow
	for rows.Next() {
		var i ListCatMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.CatID,
			&i.MediaID,
			&i.CreatedAt,
			&i.Url,
			&i.ContentType,
			&i.Muted,
			&i.IsCover,
			&i.UploaderDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
