// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catExists = `-- name: CatExists :one
select exists(select 1 from cats where id = $1) as exists
`

// lets the updates-history endpoint 404 on an unknown cat instead of
// silently returning an empty page indistinguishable from "no history yet".
func (q *Queries) CatExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, catExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCatByID = `-- name: GetCatByID :one
select
  c.id,
  c.name,
  st_x(c.area::geometry)::float8 as lng,
  st_y(c.area::geometry)::float8 as lat,
  c.photo_url,
  c.created_at,
  c.last_update_at
from cats c
where c.id = $1
`

type GetCatByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         pgtype.Text        `json:"name"`
	Lng          float64            `json:"lng"`
	Lat          float64            `json:"lat"`
	PhotoUrl     pgtype.Text        `json:"photo_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastUpdateAt pgtype.Timestamptz `json:"last_update_at"`
}

// traits are fetched separately via ListCatTraits (join against the traits
// vocabulary) rather than aggregated in here, so each trait can carry its
// display_name without hand-rolling composite-type aggregation in sql.
func (q *Queries) GetCatByID(ctx context.Context, id pgtype.UUID) (GetCatByIDRow, error) {
	row := q.db.QueryRow(ctx, getCatByID, id)
	var i GetCatByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lng,
		&i.Lat,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.LastUpdateAt,
	)
	return i, err
}

const listCatsInBounds = `-- name: ListCatsInBounds :many
select
  id,
  photo_url,
  st_x(area::geometry)::float8 as lng,
  st_y(area::geometry)::float8 as lat,
  (needs_help_until is not null and needs_help_until > now()) as needs_help,
  last_update_at
from cats
where status = 'active'
  and area && st_setsrid(
    st_makeenvelope($1::float8, $2::float8, $3::float8, $4::float8),
    4326
  )::geography
order by created_at desc
`

type ListCatsInBoundsParams struct {
	MinLng float64 `json:"min_lng"`
	MinLat float64 `json:"min_lat"`
	MaxLng float64 `json:"max_lng"`
	MaxLat float64 `json:"max_lat"`
}

type ListCatsInBoundsRow struct {
	ID           pgtype.UUID        `json:"id"`
	PhotoUrl     pgtype.Text        `json:"photo_url"`
	Lng          float64            `json:"lng"`
	Lat          float64            `json:"lat"`
	NeedsHelp    pgtype.Bool        `json:"needs_help"`
	LastUpdateAt pgtype.Timestamptz `json:"last_update_at"`
}

// area && envelope::geography uses cats_area_gix (gist on geography supports
// the && bounding-box operator); st_makeenvelope builds the requested viewport.
func (q *Queries) ListCatsInBounds(ctx context.Context, arg ListCatsInBoundsParams) ([]ListCatsInBoundsRow, error) {
	rows, err := q.db.Query(ctx, listCatsInBounds,
		arg.MinLng,
		arg.MinLat,
		arg.MaxLng,
		arg.MaxLat,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatsInBoundsRow
	for rows.Next() {
		var i ListCatsInBoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.PhotoUrl,
			&i.Lng,
			&i.Lat,
			&i.NeedsHelp,
			&i.LastUpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCat = `-- name: UpsertCat :one
insert into cats (id, name, area, photo_url, status, last_update_at, needs_help_until)
values (
  $1,
  $2,
  st_setsrid(st_makepoint($3::float8, $4::float8), 4326)::geography,
  $5,
  $6,
  $7,
  $8
)
on conflict (id) do update set
  name = excluded.name,
  area = excluded.area,
  photo_url = excluded.photo_url,
  status = excluded.status,
  last_update_at = excluded.last_update_at,
  needs_help_until = excluded.needs_help_until
returning id
`

type UpsertCatParams struct {
	ID             pgtype.UUID        `json:"id"`
	Name           pgtype.Text        `json:"name"`
	Lng            float64            `json:"lng"`
	Lat            float64            `json:"lat"`
	PhotoUrl       pgtype.Text        `json:"photo_url"`
	Status         string             `json:"status"`
	LastUpdateAt   pgtype.Timestamptz `json:"last_update_at"`
	NeedsHelpUntil pgtype.Timestamptz `json:"needs_help_until"`
}

func (q *Queries) UpsertCat(ctx context.Context, arg UpsertCatParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCat,
		arg.ID,
		arg.Name,
		arg.Lng,
		arg.Lat,
		arg.PhotoUrl,
		arg.Status,
		arg.LastUpdateAt,
		arg.NeedsHelpUntil,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
