// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catExists = `-- name: CatExists :one
select exists(select 1 from cats where id = $1) as exists
`

// lets the updates-history endpoint 404 on an unknown cat instead of
// silently returning an empty page indistinguishable from "no history yet".
func (q *Queries) CatExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, catExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCat = `-- name: CreateCat :one
insert into cats (id, name, area, primary_photo_id, status, created_by_user_id, created_by_device_id, idempotency_key)
values (
  $1,
  $2,
  st_setsrid(st_makepoint($3::float8, $4::float8), 4326)::geography,
  $5,
  'active',
  $6,
  $7,
  $8
)
on conflict (created_by_user_id, idempotency_key) where idempotency_key is not null do nothing
returning id, name, area_label, primary_photo_id, status, created_by_user_id, created_by_device_id, created_at, last_update_at,
  st_x(area::geometry)::float8 as lng, st_y(area::geometry)::float8 as lat
`

type CreateCatParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              pgtype.Text `json:"name"`
	Lng               float64     `json:"lng"`
	Lat               float64     `json:"lat"`
	PrimaryPhotoID    pgtype.UUID `json:"primary_photo_id"`
	CreatedByUserID   pgtype.UUID `json:"created_by_user_id"`
	CreatedByDeviceID pgtype.UUID `json:"created_by_device_id"`
	IdempotencyKey    pgtype.Text `json:"idempotency_key"`
}

type CreateCatRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              pgtype.Text        `json:"name"`
	AreaLabel         pgtype.Text        `json:"area_label"`
	PrimaryPhotoID    pgtype.UUID        `json:"primary_photo_id"`
	Status            string             `json:"status"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedByDeviceID pgtype.UUID        `json:"created_by_device_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastUpdateAt      pgtype.Timestamptz `json:"last_update_at"`
	Lng               float64            `json:"lng"`
	Lat               float64            `json:"lat"`
}

// issue #70: created_by_user_id is required (resolved from the
// authenticated bearer session, never client-supplied); created_by_device_id
// is optional (X-Device-Token, installation/abuse-control association only).
// area_label stays null — there is no runtime reverse-geocoding service
// (see docs/architecture/db.md), matching how seed data is the only current
// source of that field. last_update_at is left null: cat creation does not
// itself post an update (docs/product/updates.md defines freshness purely
// from actual updates), so a newly created cat starts in the same
// long_not_seen state any never-updated cat would. idempotent by
// construction, same shape as CreateMedia: on conflict do nothing on the
// partial (created_by_user_id, idempotency_key) unique index means a
// retried creation with the same key never creates a second cat — no row
// comes back on the conflicting retry, and the caller (CatsService) looks
// the existing row up via GetCatByIdempotencyKey instead.
// returning computes lng/lat the same way GetCatByID/ListCatsInBounds do
// (postgis geography has no plain Go scan type — see their comments) rather
// than `returning *`, so CatsService never has to special-case this row's
// shape against every other cat-reading query.
func (q *Queries) CreateCat(ctx context.Context, arg CreateCatParams) (CreateCatRow, error) {
	row := q.db.QueryRow(ctx, createCat,
		arg.ID,
		arg.Name,
		arg.Lng,
		arg.Lat,
		arg.PrimaryPhotoID,
		arg.CreatedByUserID,
		arg.CreatedByDeviceID,
		arg.IdempotencyKey,
	)
	var i CreateCatRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AreaLabel,
		&i.PrimaryPhotoID,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.LastUpdateAt,
		&i.Lng,
		&i.Lat,
	)
	return i, err
}

const getCatByID = `-- name: GetCatByID :one
select
  c.id,
  c.name,
  st_x(c.area::geometry)::float8 as lng,
  st_y(c.area::geometry)::float8 as lat,
  c.area_label,
  coalesce(c.photo_url, m.url, '') as photo_url,
  c.created_by_user_id,
  c.created_at,
  c.last_update_at,
  nh.needs_help_category,
  nh.comment as needs_help_comment,
  nh.created_at as needs_help_created_at,
  nh.needs_help_expires_at,
  seen.last_seen_at,
  fed.last_fed_at,
  water.last_water_at
from cats c
left join media m on m.id = c.primary_photo_id
left join lateral (
  select u.needs_help_category, u.comment, u.created_at, u.needs_help_expires_at
  from updates u
  where u.cat_id = c.id and u.needs_help and u.deleted_at is null
  order by u.created_at desc, u.seq desc
  limit 1
) nh on true
left join lateral (
  select u.created_at as last_seen_at
  from updates u
  join update_statuses s on s.update_id = u.id and s.status = 'seen'
  where u.cat_id = c.id and u.deleted_at is null
  order by u.created_at desc, u.seq desc
  limit 1
) seen on true
left join lateral (
  select u.created_at as last_fed_at
  from updates u
  join update_statuses s on s.update_id = u.id and s.status = 'fed'
  where u.cat_id = c.id and u.deleted_at is null
  order by u.created_at desc, u.seq desc
  limit 1
) fed on true
left join lateral (
  select u.created_at as last_water_at
  from updates u
  join update_statuses s on s.update_id = u.id and s.status = 'water_provided'
  where u.cat_id = c.id and u.deleted_at is null
  order by u.created_at desc, u.seq desc
  limit 1
) water on true
where c.id = $1
`

type GetCatByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               pgtype.Text        `json:"name"`
	Lng                float64            `json:"lng"`
	Lat                float64            `json:"lat"`
	AreaLabel          pgtype.Text        `json:"area_label"`
	PhotoUrl           string             `json:"photo_url"`
	CreatedByUserID    pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastUpdateAt       pgtype.Timestamptz `json:"last_update_at"`
	NeedsHelpCategory  pgtype.Text        `json:"needs_help_category"`
	NeedsHelpComment   pgtype.Text        `json:"needs_help_comment"`
	NeedsHelpCreatedAt pgtype.Timestamptz `json:"needs_help_created_at"`
	NeedsHelpExpiresAt pgtype.Timestamptz `json:"needs_help_expires_at"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	LastFedAt          pgtype.Timestamptz `json:"last_fed_at"`
	LastWaterAt        pgtype.Timestamptz `json:"last_water_at"`
}

// traits are fetched separately via ListCatTraits (join against the traits
// vocabulary) rather than aggregated in here, so each trait can carry its
// display_name without hand-rolling composite-type aggregation in sql. the
// lateral join is the same latest-needs-help-update lookup as
// ListCatsInBounds, unfiltered by expiry for the same reason. photo_url
// coalesce mirrors ListCatsInBounds — see its comment. last_seen_at/
// last_fed_at/last_water_at (issue #121's three-stat header parity gap)
// are each the created_at of the cat's most recent update carrying that
// structured status — one lateral per status, same shape as the nh lateral
// above, rather than a single group-by (each status's own latest update
// may not be the same row). soft-deleted updates are excluded, matching
// every other read path. created_by_user_id (issue #156) lets CatsService
// derive is_owner without a second query — a pre-#70 seed cat has it null,
// so is_owner is always false for one, matching that no account can own it.
func (q *Queries) GetCatByID(ctx context.Context, id pgtype.UUID) (GetCatByIDRow, error) {
	row := q.db.QueryRow(ctx, getCatByID, id)
	var i GetCatByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lng,
		&i.Lat,
		&i.AreaLabel,
		&i.PhotoUrl,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.LastUpdateAt,
		&i.NeedsHelpCategory,
		&i.NeedsHelpComment,
		&i.NeedsHelpCreatedAt,
		&i.NeedsHelpExpiresAt,
		&i.LastSeenAt,
		&i.LastFedAt,
		&i.LastWaterAt,
	)
	return i, err
}

const getCatByIdempotencyKey = `-- name: GetCatByIdempotencyKey :one
select id, name, area_label, primary_photo_id, status, created_by_user_id, created_by_device_id, created_at, last_update_at,
  st_x(area::geometry)::float8 as lng, st_y(area::geometry)::float8 as lat
from cats
where created_by_user_id = $1 and idempotency_key = $2
`

type GetCatByIdempotencyKeyParams struct {
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
	IdempotencyKey  pgtype.Text `json:"idempotency_key"`
}

type GetCatByIdempotencyKeyRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              pgtype.Text        `json:"name"`
	AreaLabel         pgtype.Text        `json:"area_label"`
	PrimaryPhotoID    pgtype.UUID        `json:"primary_photo_id"`
	Status            string             `json:"status"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedByDeviceID pgtype.UUID        `json:"created_by_device_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastUpdateAt      pgtype.Timestamptz `json:"last_update_at"`
	Lng               float64            `json:"lng"`
	Lat               float64            `json:"lat"`
}

func (q *Queries) GetCatByIdempotencyKey(ctx context.Context, arg GetCatByIdempotencyKeyParams) (GetCatByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getCatByIdempotencyKey, arg.CreatedByUserID, arg.IdempotencyKey)
	var i GetCatByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AreaLabel,
		&i.PrimaryPhotoID,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.LastUpdateAt,
		&i.Lng,
		&i.Lat,
	)
	return i, err
}

const listActiveNeedsHelpCatsByDistance = `-- name: ListActiveNeedsHelpCatsByDistance :many
with candidates as (
  select
    c.id,
    c.name,
    coalesce(c.photo_url, m.url, '') as photo_url,
    c.area_label,
    c.last_update_at,
    nh.needs_help_category,
    nh.comment as needs_help_comment,
    nh.created_at as needs_help_created_at,
    nh.needs_help_expires_at,
    st_distance(c.area, st_setsrid(st_makepoint($5::float8, $6::float8), 4326)::geography)::float8 as distance_m
  from cats c
  left join media m on m.id = c.primary_photo_id
  left join lateral (
    select u.needs_help_category, u.comment, u.created_at, u.needs_help_expires_at
    from updates u
    where u.cat_id = c.id and u.needs_help and u.deleted_at is null
    order by u.created_at desc, u.seq desc
    limit 1
  ) nh on true
  where c.status = 'active'
)
select id, name, photo_url, area_label, last_update_at, needs_help_category, needs_help_comment, needs_help_created_at, needs_help_expires_at, distance_m
from candidates
where needs_help_expires_at is not null
  and needs_help_expires_at > $1::timestamptz
  and (
    $2::float8 is null
    or distance_m > $2::float8
    or (distance_m = $2::float8 and id > $3::uuid)
  )
order by distance_m asc, id asc
limit $4
`

type ListActiveNeedsHelpCatsByDistanceParams struct {
	Now            pgtype.Timestamptz `json:"now"`
	AfterDistanceM pgtype.Float8      `json:"after_distance_m"`
	AfterID        pgtype.UUID        `json:"after_id"`
	RowLimit       int32              `json:"row_limit"`
	Lng            float64            `json:"lng"`
	Lat            float64            `json:"lat"`
}

type ListActiveNeedsHelpCatsByDistanceRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               pgtype.Text        `json:"name"`
	PhotoUrl           string             `json:"photo_url"`
	AreaLabel          pgtype.Text        `json:"area_label"`
	LastUpdateAt       pgtype.Timestamptz `json:"last_update_at"`
	NeedsHelpCategory  pgtype.Text        `json:"needs_help_category"`
	NeedsHelpComment   pgtype.Text        `json:"needs_help_comment"`
	NeedsHelpCreatedAt pgtype.Timestamptz `json:"needs_help_created_at"`
	NeedsHelpExpiresAt pgtype.Timestamptz `json:"needs_help_expires_at"`
	DistanceM          float64            `json:"distance_m"`
}

// issue #82: powers GET /v1/cats/discover?filter=needs_help — the same
// nearest-first, keyset-paginated shape as ListCatsByDistance above, plus
// one more predicate: only a cat whose latest needs-help update is both
// present and not yet expired, decided by comparing needs_help_expires_at
// against sqlc.arg(now) rather than the database's own now(). now is
// CatsService's injected clock (the same one deriveActiveAlert already
// compares every other active-alert decision against) — passed down
// explicitly so this query's filtering and CatsService's response-shaping
// of the identical row always agree on what "active" meant at the same
// instant, and so a test can hold that instant fixed at an exact expiry
// boundary the way cats_test.go already does for deriveActiveAlert. An
// expired needs-help update is never deleted or rewritten (see db.md) — it
// simply stops matching this filter, exactly like it stops being anyone's
// "latest active" alert on the map/cat-detail read paths.
func (q *Queries) ListActiveNeedsHelpCatsByDistance(ctx context.Context, arg ListActiveNeedsHelpCatsByDistanceParams) ([]ListActiveNeedsHelpCatsByDistanceRow, error) {
	rows, err := q.db.Query(ctx, listActiveNeedsHelpCatsByDistance,
		arg.Now,
		arg.AfterDistanceM,
		arg.AfterID,
		arg.RowLimit,
		arg.Lng,
		arg.Lat,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveNeedsHelpCatsByDistanceRow
	for rows.Next() {
		var i ListActiveNeedsHelpCatsByDistanceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhotoUrl,
			&i.AreaLabel,
			&i.LastUpdateAt,
			&i.NeedsHelpCategory,
			&i.NeedsHelpComment,
			&i.NeedsHelpCreatedAt,
			&i.NeedsHelpExpiresAt,
			&i.DistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatsByDistance = `-- name: ListCatsByDistance :many
with candidates as (
  select
    c.id,
    c.name,
    coalesce(c.photo_url, m.url, '') as photo_url,
    c.area_label,
    c.last_update_at,
    nh.needs_help_category,
    nh.comment as needs_help_comment,
    nh.created_at as needs_help_created_at,
    nh.needs_help_expires_at,
    st_distance(c.area, st_setsrid(st_makepoint($4::float8, $5::float8), 4326)::geography)::float8 as distance_m
  from cats c
  left join media m on m.id = c.primary_photo_id
  left join lateral (
    select u.needs_help_category, u.comment, u.created_at, u.needs_help_expires_at
    from updates u
    where u.cat_id = c.id and u.needs_help and u.deleted_at is null
    order by u.created_at desc, u.seq desc
    limit 1
  ) nh on true
  where c.status = 'active'
)
select id, name, photo_url, area_label, last_update_at, needs_help_category, needs_help_comment, needs_help_created_at, needs_help_expires_at, distance_m
from candidates
where $1::float8 is null
  or distance_m > $1::float8
  or (distance_m = $1::float8 and id > $2::uuid)
order by distance_m asc, id asc
limit $3
`

type ListCatsByDistanceParams struct {
	AfterDistanceM pgtype.Float8 `json:"after_distance_m"`
	AfterID        pgtype.UUID   `json:"after_id"`
	RowLimit       int32         `json:"row_limit"`
	Lng            float64       `json:"lng"`
	Lat            float64       `json:"lat"`
}

type ListCatsByDistanceRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               pgtype.Text        `json:"name"`
	PhotoUrl           string             `json:"photo_url"`
	AreaLabel          pgtype.Text        `json:"area_label"`
	LastUpdateAt       pgtype.Timestamptz `json:"last_update_at"`
	NeedsHelpCategory  pgtype.Text        `json:"needs_help_category"`
	NeedsHelpComment   pgtype.Text        `json:"needs_help_comment"`
	NeedsHelpCreatedAt pgtype.Timestamptz `json:"needs_help_created_at"`
	NeedsHelpExpiresAt pgtype.Timestamptz `json:"needs_help_expires_at"`
	DistanceM          float64            `json:"distance_m"`
}

// issue #82: powers GET /v1/cats/discover?filter=nearby — every active cat,
// nearest-first from the caller's own (lat, lng), keyset-paginated on
// (distance_m, id) rather than offset/limit (an inserted or deleted cat
// between two page requests must never reshuffle an already-served page,
// and a large offset would force postgres to walk and discard every row
// before it). The candidates CTE computes distance_m once so both the
// keyset predicate and the order by reference the same plain column — a
// WHERE clause can't see a SELECT list's own alias, and repeating the full
// st_distance(...) expression three times (as ListNearbyCatsForDuplicateCheck
// above tolerates once, for order by only) would get hard to keep in sync
// once a keyset predicate needs it too. distance_m uses the same
// st_distance(geography, geography) as that query, so both are backed by
// cats_area_gix (the gist index on cats.area) the same way. photo_url
// coalesce and the unfiltered-by-expiry needs-help lateral join mirror
// ListCatsInBounds/GetCatByID/ListFollowedCats exactly — CatsService is the
// one place that decides active-vs-expired, against its own injected clock.
// after_distance_m/after_id are both null on the first page (sqlc.narg);
// the row-comparison-shaped OR chain is the same pattern ListCatUpdates
// already uses for its (before_created_at, before_seq) keyset, just
// ascending instead of descending. id is an arbitrary but deterministic
// tie-breaker for the (rare, but real once two cats share a distance)
// equal-distance case — issue #82 requires "stable deterministic ordering
// for equal distances".
func (q *Queries) ListCatsByDistance(ctx context.Context, arg ListCatsByDistanceParams) ([]ListCatsByDistanceRow, error) {
	rows, err := q.db.Query(ctx, listCatsByDistance,
		arg.AfterDistanceM,
		arg.AfterID,
		arg.RowLimit,
		arg.Lng,
		arg.Lat,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatsByDistanceRow
	for rows.Next() {
		var i ListCatsByDistanceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhotoUrl,
			&i.AreaLabel,
			&i.LastUpdateAt,
			&i.NeedsHelpCategory,
			&i.NeedsHelpComment,
			&i.NeedsHelpCreatedAt,
			&i.NeedsHelpExpiresAt,
			&i.DistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatsInBounds = `-- name: ListCatsInBounds :many
select
  c.id,
  c.name,
  coalesce(c.photo_url, m.url, '') as photo_url,
  st_x(c.area::geometry)::float8 as lng,
  st_y(c.area::geometry)::float8 as lat,
  c.area_label,
  c.last_update_at,
  nh.needs_help_category,
  nh.comment as needs_help_comment,
  nh.created_at as needs_help_created_at,
  nh.needs_help_expires_at
from cats c
left join media m on m.id = c.primary_photo_id
left join lateral (
  select u.needs_help_category, u.comment, u.created_at, u.needs_help_expires_at
  from updates u
  where u.cat_id = c.id and u.needs_help and u.deleted_at is null
  order by u.created_at desc, u.seq desc
  limit 1
) nh on true
where c.status = 'active'
  and c.area && st_setsrid(
    st_makeenvelope($1::float8, $2::float8, $3::float8, $4::float8),
    4326
  )::geography
order by c.created_at desc
`

type ListCatsInBoundsParams struct {
	MinLng float64 `json:"min_lng"`
	MinLat float64 `json:"min_lat"`
	MaxLng float64 `json:"max_lng"`
	MaxLat float64 `json:"max_lat"`
}

type ListCatsInBoundsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               pgtype.Text        `json:"name"`
	PhotoUrl           string             `json:"photo_url"`
	Lng                float64            `json:"lng"`
	Lat                float64            `json:"lat"`
	AreaLabel          pgtype.Text        `json:"area_label"`
	LastUpdateAt       pgtype.Timestamptz `json:"last_update_at"`
	NeedsHelpCategory  pgtype.Text        `json:"needs_help_category"`
	NeedsHelpComment   pgtype.Text        `json:"needs_help_comment"`
	NeedsHelpCreatedAt pgtype.Timestamptz `json:"needs_help_created_at"`
	NeedsHelpExpiresAt pgtype.Timestamptz `json:"needs_help_expires_at"`
}

// area && envelope::geography uses cats_area_gix (gist on geography supports
// the && bounding-box operator); st_makeenvelope builds the requested viewport.
// name/area_label are the minimum extra fields the map-marker preview sheet
// needs (issue #21 prototype-parity correction) — no second full-detail
// fetch on marker tap. the lateral join returns each cat's latest
// needs-help update (issue #4/#23), whether or not it has since expired —
// ListNearby (service layer) is the one that decides active-vs-expired,
// against an injected clock, not this query's own now(). issue #70: a cat
// created through POST /v1/cats has primary_photo_id (media table) instead
// of photo_url (seed-only column, issue #7) — coalesce so both read paths
// resolve to the same primary_photo field.
func (q *Queries) ListCatsInBounds(ctx context.Context, arg ListCatsInBoundsParams) ([]ListCatsInBoundsRow, error) {
	rows, err := q.db.Query(ctx, listCatsInBounds,
		arg.MinLng,
		arg.MinLat,
		arg.MaxLng,
		arg.MaxLat,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatsInBoundsRow
	for rows.Next() {
		var i ListCatsInBoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhotoUrl,
			&i.Lng,
			&i.Lat,
			&i.AreaLabel,
			&i.LastUpdateAt,
			&i.NeedsHelpCategory,
			&i.NeedsHelpComment,
			&i.NeedsHelpCreatedAt,
			&i.NeedsHelpExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearbyCatsForDuplicateCheck = `-- name: ListNearbyCatsForDuplicateCheck :many
select
  c.id,
  c.name,
  coalesce(c.photo_url, m.url, '') as photo_url
from cats c
left join media m on m.id = c.primary_photo_id
where c.status = 'active'
  and st_dwithin(c.area, st_setsrid(st_makepoint($1::float8, $2::float8), 4326)::geography, $3::float8)
order by st_distance(c.area, st_setsrid(st_makepoint($1::float8, $2::float8), 4326)::geography) asc
`

type ListNearbyCatsForDuplicateCheckParams struct {
	Lng     float64 `json:"lng"`
	Lat     float64 `json:"lat"`
	RadiusM float64 `json:"radius_m"`
}

type ListNearbyCatsForDuplicateCheckRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     pgtype.Text `json:"name"`
	PhotoUrl string      `json:"photo_url"`
}

// issue #70: powers GET /v1/cats/nearby, the add-cat flow's non-blocking
// duplicate-candidate check (docs/product/cats.md, docs/product/trust.md —
// advisory only, never blocks creation on its own). st_dwithin on the
// geography column uses cats_area_gix the same way ListCatsInBounds' &&
// bounding-box check does; radius_m is in meters, matching geography's
// native unit. photo_url coalesce mirrors ListCatsInBounds/GetCatByID.
func (q *Queries) ListNearbyCatsForDuplicateCheck(ctx context.Context, arg ListNearbyCatsForDuplicateCheckParams) ([]ListNearbyCatsForDuplicateCheckRow, error) {
	rows, err := q.db.Query(ctx, listNearbyCatsForDuplicateCheck, arg.Lng, arg.Lat, arg.RadiusM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearbyCatsForDuplicateCheckRow
	for rows.Next() {
		var i ListNearbyCatsForDuplicateCheckRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PhotoUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCatCoverPhoto = `-- name: SetCatCoverPhoto :exec
update cats set primary_photo_id = $1 where id = $2
`

type SetCatCoverPhotoParams struct {
	PrimaryPhotoID pgtype.UUID `json:"primary_photo_id"`
	ID             pgtype.UUID `json:"id"`
}

// issue #156: switches a cat's cover to an existing entry from its own
// cat_media archive. CatsService verifies both ownership (created_by_user_id
// matches the caller) and gallery membership (a GetCatMediaByCatAndMedia hit)
// before ever issuing this update — this query itself trusts both checks
// already happened and only writes.
func (q *Queries) SetCatCoverPhoto(ctx context.Context, arg SetCatCoverPhotoParams) error {
	_, err := q.db.Exec(ctx, setCatCoverPhoto, arg.PrimaryPhotoID, arg.ID)
	return err
}

const updateCatLastUpdateAt = `-- name: UpdateCatLastUpdateAt :exec
update cats set last_update_at = greatest(last_update_at, $1) where id = $2
`

type UpdateCatLastUpdateAtParams struct {
	LastUpdateAt pgtype.Timestamptz `json:"last_update_at"`
	ID           pgtype.UUID        `json:"id"`
}

// issue #36: run inside the same transaction as CreateUpdate/CreateUpdateStatus
// so a new ordinary update and the cat's last_update_at commit atomically.
// issue #38: monotonic — greatest() already ignores a null argument
// (postgres greatest/least ignore nulls, returning null only when every
// argument is null), so a cat's first-ever update still sets last_update_at
// correctly. this keeps an out-of-order commit (an older update committing
// after a newer one) from moving a cat's displayed freshness backwards.
func (q *Queries) UpdateCatLastUpdateAt(ctx context.Context, arg UpdateCatLastUpdateAtParams) error {
	_, err := q.db.Exec(ctx, updateCatLastUpdateAt, arg.LastUpdateAt, arg.ID)
	return err
}

const upsertCat = `-- name: UpsertCat :one
insert into cats (id, name, area, area_label, photo_url, status, last_update_at)
values (
  $1,
  $2,
  st_setsrid(st_makepoint($3::float8, $4::float8), 4326)::geography,
  $5,
  $6,
  $7,
  $8
)
on conflict (id) do update set
  name = excluded.name,
  area = excluded.area,
  area_label = excluded.area_label,
  photo_url = excluded.photo_url,
  status = excluded.status,
  last_update_at = excluded.last_update_at
returning id
`

type UpsertCatParams struct {
	ID           pgtype.UUID        `json:"id"`
	Name         pgtype.Text        `json:"name"`
	Lng          float64            `json:"lng"`
	Lat          float64            `json:"lat"`
	AreaLabel    pgtype.Text        `json:"area_label"`
	PhotoUrl     pgtype.Text        `json:"photo_url"`
	Status       string             `json:"status"`
	LastUpdateAt pgtype.Timestamptz `json:"last_update_at"`
}

func (q *Queries) UpsertCat(ctx context.Context, arg UpsertCatParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCat,
		arg.ID,
		arg.Name,
		arg.Lng,
		arg.Lat,
		arg.AreaLabel,
		arg.PhotoUrl,
		arg.Status,
		arg.LastUpdateAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
