// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDevicePushToken = `-- name: ClearDevicePushToken :exec
update devices set push_token = null
where id = $1 and push_token = $2
`

type ClearDevicePushTokenParams struct {
	DeviceID  pgtype.UUID `json:"device_id"`
	PushToken pgtype.Text `json:"push_token"`
}

// issue #84: retires a token fcm permanently rejected (unregistered/
// invalid). The `and push_token = sqlc.arg(push_token)` guard makes the
// retirement safe against a concurrent refresh: if the client registered
// a newer token between the send attempt and this clear, zero rows match
// and the fresh token survives.
func (q *Queries) ClearDevicePushToken(ctx context.Context, arg ClearDevicePushTokenParams) error {
	_, err := q.db.Exec(ctx, clearDevicePushToken, arg.DeviceID, arg.PushToken)
	return err
}

const createDevice = `-- name: CreateDevice :one
insert into devices (id, token_hash, push_token, platform)
values ($1, $2, $3, $4)
returning id, created_at
`

type CreateDeviceParams struct {
	ID        pgtype.UUID `json:"id"`
	TokenHash string      `json:"token_hash"`
	PushToken pgtype.Text `json:"push_token"`
	Platform  string      `json:"platform"`
}

type CreateDeviceRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// stores a new device row; only the sha-256 hash of the raw token is
// persisted here — the raw token is returned to the caller once and
// never stored (see docs/architecture/db.md). push_token is optional.
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (CreateDeviceRow, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.TokenHash,
		arg.PushToken,
		arg.Platform,
	)
	var i CreateDeviceRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
select id, user_id, revoked_at
from devices
where id = $1
`

type GetDeviceByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// issue #58: read a device's current account link before deciding whether
// otp verification may link it (see LinkDeviceToUser).
func (q *Queries) GetDeviceByID(ctx context.Context, id pgtype.UUID) (GetDeviceByIDRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i GetDeviceByIDRow
	err := row.Scan(&i.ID, &i.UserID, &i.RevokedAt)
	return i, err
}

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
select id, revoked_at, user_id
from devices
where token_hash = $1
`

type GetDeviceByTokenHashRow struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

// resolves an inbound X-Device-Token to its non-secret device_id and, if
// the device has been linked to an account (issue #58), that account's id.
// the middleware calls this after hashing the presented token; only
// the non-secret fields are returned — the hash is never echoed back.
func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash string) (GetDeviceByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByTokenHash, tokenHash)
	var i GetDeviceByTokenHashRow
	err := row.Scan(&i.ID, &i.RevokedAt, &i.UserID)
	return i, err
}

const linkDeviceToUser = `-- name: LinkDeviceToUser :exec
update devices set user_id = $1 where id = $2
`

type LinkDeviceToUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

// issue #58: idempotent by construction — setting user_id to the same
// value on a retry (or on a device already linked to this exact account)
// is a no-op update. the service layer rejects linking a device already
// linked to a *different* account before this query ever runs. A device
// stays linked to at most one account at a time, but issue #80's
// UnlinkDeviceFromUser (below) can clear that link on logout so the same
// installation can later link to a different account.
func (q *Queries) LinkDeviceToUser(ctx context.Context, arg LinkDeviceToUserParams) error {
	_, err := q.db.Exec(ctx, linkDeviceToUser, arg.UserID, arg.ID)
	return err
}

const setDevicePushToken = `-- name: SetDevicePushToken :exec
with cleared as (
  update devices d set push_token = null
  where d.push_token = $1 and d.id != $2
)
update devices set push_token = $1
where devices.id = $2
`

type SetDevicePushTokenParams struct {
	PushToken pgtype.Text `json:"push_token"`
	DeviceID  pgtype.UUID `json:"device_id"`
}

// issue #84: registers/refreshes the fcm token for one installation. The
// cte clears the same token off any *other* device row first: a client
// that lost its device credential re-registers (new devices row) but the
// installation's fcm token stays the same, and without this clear both
// rows would carry the token and one needs-help update would push the
// same physical device twice. In-place update on rotation — the device
// row is the installation identity, so a refreshed token never creates a
// second row (issue #84's no-duplicate-installations constraint).
func (q *Queries) SetDevicePushToken(ctx context.Context, arg SetDevicePushTokenParams) error {
	_, err := q.db.Exec(ctx, setDevicePushToken, arg.PushToken, arg.DeviceID)
	return err
}

const unlinkDeviceFromUser = `-- name: UnlinkDeviceFromUser :exec
update devices set user_id = null
where id = $1 and user_id = $2
`

type UnlinkDeviceFromUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// issue #80 (product-owner review): clears a device's account link on
// logout, so the same installation can sign into a *different* account
// afterward without linkDevice's "already linked to a different account"
// check rejecting it forever. The `and user_id = sqlc.arg(user_id)` guard
// is the entire safety mechanism: this only ever clears a link that
// currently matches the caller's own account — a mismatched, stale, or
// already-unlinked device affects zero rows, never another account's
// link. Never touches follows/updates/any other ownership data; those
// stay attributed to whichever account actually authored them, forever.
func (q *Queries) UnlinkDeviceFromUser(ctx context.Context, arg UnlinkDeviceFromUserParams) error {
	_, err := q.db.Exec(ctx, unlinkDeviceFromUser, arg.ID, arg.UserID)
	return err
}
