// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
insert into devices (id, token_hash, push_token, platform)
values ($1, $2, $3, $4)
returning id, created_at
`

type CreateDeviceParams struct {
	ID        pgtype.UUID `json:"id"`
	TokenHash string      `json:"token_hash"`
	PushToken pgtype.Text `json:"push_token"`
	Platform  string      `json:"platform"`
}

type CreateDeviceRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// stores a new device row; only the sha-256 hash of the raw token is
// persisted here — the raw token is returned to the caller once and
// never stored (see docs/architecture/db.md). push_token is optional.
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (CreateDeviceRow, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.TokenHash,
		arg.PushToken,
		arg.Platform,
	)
	var i CreateDeviceRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
select id, revoked_at
from devices
where token_hash = $1
`

type GetDeviceByTokenHashRow struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// resolves an inbound X-Device-Token to its non-secret device_id.
// the middleware calls this after hashing the presented token; only
// the non-secret fields are returned — the hash is never echoed back.
func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash string) (GetDeviceByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByTokenHash, tokenHash)
	var i GetDeviceByTokenHashRow
	err := row.Scan(&i.ID, &i.RevokedAt)
	return i, err
}
