// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillFollowsUserID = `-- name: BackfillFollowsUserID :exec
update follows set user_id = $1
where device_id = $2 and user_id is null
`

type BackfillFollowsUserIDParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

// issue #65: called inside AuthService.linkDevice's transaction, once a
// device is linked (or re-verified as already linked) to an account.
// idempotent — only rows still missing user_id are touched, so calling this
// repeatedly (retries, re-verification) never reassigns an already-set
// owner. Conflict-safe against follows_user_cat_uq only because
// DeleteRedundantDeviceFollows already ran first in the same transaction
// (issue #71) — a device can have at most one follow per cat
// (follows_device_cat_uq), so at most one row here can still be
// unbackfilled for a given cat once duplicates are gone.
func (q *Queries) BackfillFollowsUserID(ctx context.Context, arg BackfillFollowsUserIDParams) error {
	_, err := q.db.Exec(ctx, backfillFollowsUserID, arg.UserID, arg.DeviceID)
	return err
}

const createFollow = `-- name: CreateFollow :exec
insert into follows (user_id, device_id, cat_id)
values ($1, $2, $3)
on conflict (user_id, cat_id) where user_id is not null do nothing
`

type CreateFollowParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	DeviceID pgtype.UUID `json:"device_id"`
	CatID    pgtype.UUID `json:"cat_id"`
}

// issue #65: account-owned. user_id is required (resolved from the
// authenticated bearer session, never client-supplied); device_id is
// optional (X-Device-Token, for installation/abuse-control association
// only — it is never sufficient authorization on its own). idempotent by
// construction: on conflict do nothing on the partial (user_id, cat_id)
// unique index means a repeat follow for the same account/cat pair —
// including two concurrent duplicate requests — leaves exactly one row,
// never an error or a duplicate.
func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) error {
	_, err := q.db.Exec(ctx, createFollow, arg.UserID, arg.DeviceID, arg.CatID)
	return err
}

const deleteFollow = `-- name: DeleteFollow :exec
delete from follows where user_id = $1 and cat_id = $2
`

type DeleteFollowParams struct {
	UserID pgtype.UUID `json:"user_id"`
	CatID  pgtype.UUID `json:"cat_id"`
}

// issue #65: account-scoped. idempotent: unfollowing a cat this account
// doesn't currently follow deletes zero rows and succeeds silently rather
// than erroring.
func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFollow, arg.UserID, arg.CatID)
	return err
}

const deleteRedundantDeviceFollows = `-- name: DeleteRedundantDeviceFollows :exec
delete from follows f
where f.device_id = $1
  and f.user_id is null
  and exists (
    select 1 from follows owned
    where owned.cat_id = f.cat_id and owned.user_id = $2
  )
`

type DeleteRedundantDeviceFollowsParams struct {
	DeviceID pgtype.UUID `json:"device_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// issue #71: called inside AuthService.linkDevice's transaction,
// immediately before BackfillFollowsUserID. Deletes this device's
// not-yet-backfilled follow rows that are pure duplicates of a follow the
// target account already owns for the same cat (from a previous device
// link, or a direct account follow) — the account already effectively
// follows that cat, so the duplicate carries no new information. This is
// what keeps BackfillFollowsUserID's plain assignment below conflict-safe
// against follows_user_cat_uq: after this delete, at most one
// not-yet-owned row remains per cat for this device.
func (q *Queries) DeleteRedundantDeviceFollows(ctx context.Context, arg DeleteRedundantDeviceFollowsParams) error {
	_, err := q.db.Exec(ctx, deleteRedundantDeviceFollows, arg.DeviceID, arg.UserID)
	return err
}

const listFollowedCats = `-- name: ListFollowedCats :many
select
  c.id,
  c.name,
  coalesce(c.photo_url, m.url, '') as photo_url,
  st_x(c.area::geometry)::float8 as lng,
  st_y(c.area::geometry)::float8 as lat,
  c.area_label,
  c.last_update_at,
  nh.needs_help_category,
  nh.comment as needs_help_comment,
  nh.created_at as needs_help_created_at,
  nh.needs_help_expires_at
from follows f
join cats c on c.id = f.cat_id
left join media m on m.id = c.primary_photo_id
left join lateral (
  select u.needs_help_category, u.comment, u.created_at, u.needs_help_expires_at
  from updates u
  where u.cat_id = c.id and u.needs_help and u.deleted_at is null
  order by u.created_at desc, u.seq desc
  limit 1
) nh on true
where f.user_id = $1
  -- issue #234: a followed cat whose owner this account has since blocked
  -- drops out of the list. The follow row itself is left alone, so
  -- unblocking restores it without the user having to follow again. The
  -- viewer is always the list's own owner (this read is never public), so
  -- it reuses user_id instead of taking a separate viewer argument.
  and not exists (
    select 1 from user_blocks b
    where b.blocker_user_id = $1
      and b.blocked_user_id = c.created_by_user_id
  )
order by c.last_update_at desc nulls last, c.id desc
`

type ListFollowedCatsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               pgtype.Text        `json:"name"`
	PhotoUrl           string             `json:"photo_url"`
	Lng                float64            `json:"lng"`
	Lat                float64            `json:"lat"`
	AreaLabel          pgtype.Text        `json:"area_label"`
	LastUpdateAt       pgtype.Timestamptz `json:"last_update_at"`
	NeedsHelpCategory  pgtype.Text        `json:"needs_help_category"`
	NeedsHelpComment   pgtype.Text        `json:"needs_help_comment"`
	NeedsHelpCreatedAt pgtype.Timestamptz `json:"needs_help_created_at"`
	NeedsHelpExpiresAt pgtype.Timestamptz `json:"needs_help_expires_at"`
}

// issue #65: an account's followed cats, ordered by most recent cat
// activity. last_update_at desc nulls last puts a cat that has never had an
// update after every cat that has, however old — no activity is never
// "fresher" than old activity. c.id desc is the deterministic tie-breaker
// for equal last_update_at, including the shared-null case, since
// last_update_at alone can't order two never-updated cats against each
// other. joins cats (not just follows) so the response carries the same
// cat-summary shape as the map/detail endpoints, including each cat's
// latest needs-help update via the same unfiltered-by-expiry lateral join
// as ListCatsInBounds/GetCatByID — the service layer decides
// active-vs-expired against its own injected clock, never this query's own
// now().
func (q *Queries) ListFollowedCats(ctx context.Context, userID pgtype.UUID) ([]ListFollowedCatsRow, error) {
	rows, err := q.db.Query(ctx, listFollowedCats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowedCatsRow
	for rows.Next() {
		var i ListFollowedCatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhotoUrl,
			&i.Lng,
			&i.Lat,
			&i.AreaLabel,
			&i.LastUpdateAt,
			&i.NeedsHelpCategory,
			&i.NeedsHelpComment,
			&i.NeedsHelpCreatedAt,
			&i.NeedsHelpExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNeedsHelpRecipientDevices = `-- name: ListNeedsHelpRecipientDevices :many
select distinct d.id as device_id, d.push_token
from follows f
join devices d on d.user_id = f.user_id
join cats c on c.id = f.cat_id
where f.cat_id = $1
  and f.user_id is not null
  and f.user_id != $2
  and d.revoked_at is null
  and not exists (
    select 1 from user_blocks b
    where b.blocker_user_id = f.user_id
      and b.blocked_user_id = c.created_by_user_id
  )
`

type ListNeedsHelpRecipientDevicesParams struct {
	CatID        pgtype.UUID `json:"cat_id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
}

type ListNeedsHelpRecipientDevicesRow struct {
	DeviceID  pgtype.UUID `json:"device_id"`
	PushToken pgtype.Text `json:"push_token"`
}

// issue #78: the notification worker's recipient-resolution step for one
// needs-help update. Joins account-owned follows (never device-owned ones
// — following, like the update itself, is account state) to that
// account's linked devices. author_user_id excludes the reporter from
// their own notification without a separate filter step; revoked_at is
// null excludes a device the account has since revoked; device_id is
// distinct in case a future schema allows more than one follow row per
// (user_id, cat_id), which follows_user_cat_uq today prevents but this
// query shouldn't rely on. never joins on device_id — only account
// ownership (user_id) determines who follows a cat, per [[community]]'s
// private-following contract; devices are purely the push-delivery target.
// push_token rides along (issue #84) so the worker can hand the fcm
// sender a real delivery address; a null push_token device still gets its
// in-app notifications row (the source of truth independent of push —
// issue #84), it just isn't pushed to.
// issue #234: a follower who blocks the *cat's owner* is dropped from the
// recipient list. Without this, blocking would hide the cat while its
// needs-help pushes kept arriving and deep-linking into a screen that now
// answers 404. The predicate keys on cats.created_by_user_id, not on the
// update's author: what a block hides is everything attached to the cats
// that account owns, whoever wrote the individual update.
func (q *Queries) ListNeedsHelpRecipientDevices(ctx context.Context, arg ListNeedsHelpRecipientDevicesParams) ([]ListNeedsHelpRecipientDevicesRow, error) {
	rows, err := q.db.Query(ctx, listNeedsHelpRecipientDevices, arg.CatID, arg.AuthorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNeedsHelpRecipientDevicesRow
	for rows.Next() {
		var i ListNeedsHelpRecipientDevicesRow
		if err := rows.Scan(&i.DeviceID, &i.PushToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
