// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
insert into media (id, object_key, url, content_type, byte_size, uploaded_by_user_id, uploaded_by_device_id, idempotency_key)
values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (uploaded_by_user_id, idempotency_key) where idempotency_key is not null do nothing
returning id, object_key, url, content_type, byte_size, uploaded_by_user_id, uploaded_by_device_id, idempotency_key, created_at
`

type CreateMediaParams struct {
	ID                 pgtype.UUID `json:"id"`
	ObjectKey          string      `json:"object_key"`
	Url                string      `json:"url"`
	ContentType        string      `json:"content_type"`
	ByteSize           int32       `json:"byte_size"`
	UploadedByUserID   pgtype.UUID `json:"uploaded_by_user_id"`
	UploadedByDeviceID pgtype.UUID `json:"uploaded_by_device_id"`
	IdempotencyKey     pgtype.Text `json:"idempotency_key"`
}

// issue #70: uploaded_by_user_id is required (resolved from the
// authenticated bearer session, never client-supplied); uploaded_by_device_id
// is optional (X-Device-Token, installation/abuse-control association only).
// idempotent by construction: on conflict do nothing on the partial
// (uploaded_by_user_id, idempotency_key) unique index means a retried
// upload with the same key never creates a second row — no row comes back
// (pgx.ErrNoRows) on the conflicting retry, and the caller (MediaService)
// looks the existing row up via GetMediaByIdempotencyKey instead.
func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.ID,
		arg.ObjectKey,
		arg.Url,
		arg.ContentType,
		arg.ByteSize,
		arg.UploadedByUserID,
		arg.UploadedByDeviceID,
		arg.IdempotencyKey,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Url,
		&i.ContentType,
		&i.ByteSize,
		&i.UploadedByUserID,
		&i.UploadedByDeviceID,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
select id, object_key, url, content_type, byte_size, uploaded_by_user_id, uploaded_by_device_id, idempotency_key, created_at from media where id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Url,
		&i.ContentType,
		&i.ByteSize,
		&i.UploadedByUserID,
		&i.UploadedByDeviceID,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaByIdempotencyKey = `-- name: GetMediaByIdempotencyKey :one
select id, object_key, url, content_type, byte_size, uploaded_by_user_id, uploaded_by_device_id, idempotency_key, created_at from media where uploaded_by_user_id = $1 and idempotency_key = $2
`

type GetMediaByIdempotencyKeyParams struct {
	UploadedByUserID pgtype.UUID `json:"uploaded_by_user_id"`
	IdempotencyKey   pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetMediaByIdempotencyKey(ctx context.Context, arg GetMediaByIdempotencyKeyParams) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByIdempotencyKey, arg.UploadedByUserID, arg.IdempotencyKey)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.ObjectKey,
		&i.Url,
		&i.ContentType,
		&i.ByteSize,
		&i.UploadedByUserID,
		&i.UploadedByDeviceID,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}
