// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cat struct {
	ID           pgtype.UUID        `json:"id"`
	Name         pgtype.Text        `json:"name"`
	Area         interface{}        `json:"area"`
	PhotoUrl     pgtype.Text        `json:"photo_url"`
	Status       string             `json:"status"`
	LastUpdateAt pgtype.Timestamptz `json:"last_update_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AreaLabel    pgtype.Text        `json:"area_label"`
}

type CatTrait struct {
	CatID    pgtype.UUID `json:"cat_id"`
	TraitKey string      `json:"trait_key"`
}

type Device struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	PushToken pgtype.Text        `json:"push_token"`
	Platform  string             `json:"platform"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationOutbox struct {
	ID          pgtype.UUID        `json:"id"`
	UpdateID    pgtype.UUID        `json:"update_id"`
	CatID       pgtype.UUID        `json:"cat_id"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Trait struct {
	Key         string             `json:"key"`
	DisplayName string             `json:"display_name"`
	Active      bool               `json:"active"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	GroupKey    pgtype.Text        `json:"group_key"`
}

type TraitGroup struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	SortOrder   int32  `json:"sort_order"`
}

type Update struct {
	ID                 pgtype.UUID        `json:"id"`
	CatID              pgtype.UUID        `json:"cat_id"`
	Comment            pgtype.Text        `json:"comment"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Seq                pgtype.Int8        `json:"seq"`
	Kind               string             `json:"kind"`
	NeedsHelpCategory  pgtype.Text        `json:"needs_help_category"`
	NeedsHelpExpiresAt pgtype.Timestamptz `json:"needs_help_expires_at"`
	AuthorDeviceID     pgtype.UUID        `json:"author_device_id"`
}

type UpdateStatus struct {
	UpdateID pgtype.UUID `json:"update_id"`
	Status   string      `json:"status"`
}

type WorkspacePing struct {
	ID        pgtype.UUID        `json:"id"`
	Message   string             `json:"message"`
	Location  interface{}        `json:"location"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
