// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
insert into notifications (id, device_id, cat_id, update_id)
values ($1, $2, $3, $4)
on conflict (device_id, update_id) do nothing
returning id, device_id, cat_id, update_id, read_at, created_at
`

type CreateNotificationParams struct {
	ID       pgtype.UUID `json:"id"`
	DeviceID pgtype.UUID `json:"device_id"`
	CatID    pgtype.UUID `json:"cat_id"`
	UpdateID pgtype.UUID `json:"update_id"`
}

// issue #78: the notification worker's delivery-dedup insert. on conflict
// (device_id, update_id) do nothing means a retried or concurrently-run
// dispatch of the same outbox row never creates a second delivery record
// for the same device — no row comes back (pgx.ErrNoRows) on the
// conflicting attempt, and the caller (NotificationService.DispatchPending)
// treats that as "already delivered, don't send again" rather than an
// error (mirrors db/queries/media.sql's CreateMedia idiom).
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.DeviceID,
		arg.CatID,
		arg.UpdateID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CatID,
		&i.UpdateID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMyNotifications = `-- name: ListMyNotifications :many
select
  n.id,
  n.cat_id,
  n.update_id,
  n.read_at,
  n.created_at
from notifications n
join devices d on d.id = n.device_id
where d.user_id = $1
  and (
    $2::timestamptz is null
    or n.created_at < $2::timestamptz
    or (n.created_at = $2::timestamptz and n.id < $3::uuid)
  )
order by n.created_at desc, n.id desc
limit $4::int
`

type ListMyNotificationsParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        pgtype.UUID        `json:"before_id"`
	RowLimit        int32              `json:"row_limit"`
}

type ListMyNotificationsRow struct {
	ID        pgtype.UUID        `json:"id"`
	CatID     pgtype.UUID        `json:"cat_id"`
	UpdateID  pgtype.UUID        `json:"update_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// issue #78: newest-first keyset pagination for GET /v1/me/notifications,
// mirroring db/queries/updates.sql's ListCatUpdates shape. device_id is
// resolved from the caller's linked devices (join, not a bare where), so
// an account only ever sees notifications delivered to a device it
// currently owns — never another account's, even a former owner of the
// same device (LinkDeviceToUser only ever adds an owner, see
// docs/architecture/db.md, so this can't leak a stale link either).
func (q *Queries) ListMyNotifications(ctx context.Context, arg ListMyNotificationsParams) ([]ListMyNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listMyNotifications,
		arg.UserID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyNotificationsRow
	for rows.Next() {
		var i ListMyNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CatID,
			&i.UpdateID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
update notifications n
set read_at = $1
from devices d
where n.device_id = d.id
  and n.id = $2
  and d.user_id = $3
`

type MarkNotificationReadParams struct {
	ReadAt pgtype.Timestamptz `json:"read_at"`
	ID     pgtype.UUID        `json:"id"`
	UserID pgtype.UUID        `json:"user_id"`
}

// issue #78: owner-scoped through the same devices.user_id join
// ListMyNotifications uses, so marking a notification read can never
// affect a row belonging to another account's device. idempotent —
// marking an already-read notification read again just re-sets the same
// timestamp semantics (still "read"), never errors.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ReadAt, arg.ID, arg.UserID)
	return err
}
