// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_outbox.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationOutbox = `-- name: CreateNotificationOutbox :exec
insert into notification_outbox (update_id, cat_id)
values ($1, $2)
`

type CreateNotificationOutboxParams struct {
	UpdateID pgtype.UUID `json:"update_id"`
	CatID    pgtype.UUID `json:"cat_id"`
}

// issue #38: explicit enqueue replaces the removed updates_enqueue_outbox
// trigger (migration 00009) — Store.CreateOrdinaryUpdate is now the only
// caller, inside the same transaction as the update/statuses/last_update_at
// writes, so only an authenticated ordinary write ever produces outbox
// work. notification_outbox.update_id is unique, so retrying or repeating
// an enqueue for the same update fails loudly (and rolls the whole
// transaction back) instead of duplicating work.
func (q *Queries) CreateNotificationOutbox(ctx context.Context, arg CreateNotificationOutboxParams) error {
	_, err := q.db.Exec(ctx, createNotificationOutbox, arg.UpdateID, arg.CatID)
	return err
}
