// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp_codes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOtpCodeIfValid = `-- name: ConsumeOtpCodeIfValid :one
update otp_codes as o
set consumed_at = $1
where o.id = $2
  and o.code_hash = $3
  and o.consumed_at is null
  and o.expires_at > $4
  and o.attempts < o.max_attempts
  and o.id = (
    select latest.id from otp_codes as latest
    where latest.phone = $5
    order by latest.created_at desc
    limit 1
  )
returning o.id
`

type ConsumeOtpCodeIfValidParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ID         pgtype.UUID        `json:"id"`
	CodeHash   string             `json:"code_hash"`
	Now        pgtype.Timestamptz `json:"now"`
	Phone      string             `json:"phone"`
}

// atomic compare-and-set (code review fix, issue #58): the previous
// read-then-unconditional-update let two concurrent verifications of the
// same code both pass validation in application code before either wrote
// consumed_at, so both could proceed to account linking and session
// issuance. this single statement re-evaluates every validity predicate
// (still the phone's latest code, unconsumed, unexpired, attempts
// remaining) atomically against the row's current committed state; a
// concurrent loser's update commits after the winner's and matches zero
// rows, since consumed_at is no longer null by the time it runs. the
// "still the latest" subquery preserves the existing "only the most
// recently issued code is ever checked" behavior — a race can't smuggle in
// consumption of a superseded code.
func (q *Queries) ConsumeOtpCodeIfValid(ctx context.Context, arg ConsumeOtpCodeIfValidParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeOtpCodeIfValid,
		arg.ConsumedAt,
		arg.ID,
		arg.CodeHash,
		arg.Now,
		arg.Phone,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createOtpCode = `-- name: CreateOtpCode :one
insert into otp_codes (id, phone, code_hash, max_attempts, expires_at)
values ($1, $2, $3, $4, $5)
returning id, created_at
`

type CreateOtpCodeParams struct {
	ID          pgtype.UUID        `json:"id"`
	Phone       string             `json:"phone"`
	CodeHash    string             `json:"code_hash"`
	MaxAttempts int32              `json:"max_attempts"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type CreateOtpCodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOtpCode(ctx context.Context, arg CreateOtpCodeParams) (CreateOtpCodeRow, error) {
	row := q.db.QueryRow(ctx, createOtpCode,
		arg.ID,
		arg.Phone,
		arg.CodeHash,
		arg.MaxAttempts,
		arg.ExpiresAt,
	)
	var i CreateOtpCodeRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getLatestOtpCode = `-- name: GetLatestOtpCode :one
select id, phone, code_hash, attempts, max_attempts, expires_at, consumed_at, created_at
from otp_codes
where phone = $1
order by created_at desc
limit 1
`

// the most recently issued code for a phone number, regardless of whether
// it's already consumed or expired — the service layer decides validity
// against its own injected clock so behavior stays deterministically
// testable (issue #58).
func (q *Queries) GetLatestOtpCode(ctx context.Context, phone string) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestOtpCode, phone)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOtpAttempts = `-- name: IncrementOtpAttempts :exec
update otp_codes set attempts = attempts + 1 where id = $1
`

func (q *Queries) IncrementOtpAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOtpAttempts, id)
	return err
}
