// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp_codes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOtpCode = `-- name: ConsumeOtpCode :exec
update otp_codes set consumed_at = $1 where id = $2
`

type ConsumeOtpCodeParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) ConsumeOtpCode(ctx context.Context, arg ConsumeOtpCodeParams) error {
	_, err := q.db.Exec(ctx, consumeOtpCode, arg.ConsumedAt, arg.ID)
	return err
}

const createOtpCode = `-- name: CreateOtpCode :one
insert into otp_codes (id, phone, code_hash, max_attempts, expires_at)
values ($1, $2, $3, $4, $5)
returning id, created_at
`

type CreateOtpCodeParams struct {
	ID          pgtype.UUID        `json:"id"`
	Phone       string             `json:"phone"`
	CodeHash    string             `json:"code_hash"`
	MaxAttempts int32              `json:"max_attempts"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type CreateOtpCodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOtpCode(ctx context.Context, arg CreateOtpCodeParams) (CreateOtpCodeRow, error) {
	row := q.db.QueryRow(ctx, createOtpCode,
		arg.ID,
		arg.Phone,
		arg.CodeHash,
		arg.MaxAttempts,
		arg.ExpiresAt,
	)
	var i CreateOtpCodeRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getLatestOtpCode = `-- name: GetLatestOtpCode :one
select id, phone, code_hash, attempts, max_attempts, expires_at, consumed_at, created_at
from otp_codes
where phone = $1
order by created_at desc
limit 1
`

// the most recently issued code for a phone number, regardless of whether
// it's already consumed or expired — the service layer decides validity
// against its own injected clock so behavior stays deterministically
// testable (issue #58).
func (q *Queries) GetLatestOtpCode(ctx context.Context, phone string) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestOtpCode, phone)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOtpAttempts = `-- name: IncrementOtpAttempts :exec
update otp_codes set attempts = attempts + 1 where id = $1
`

func (q *Queries) IncrementOtpAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOtpAttempts, id)
	return err
}
