// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCatSummariesByIDs = `-- name: GetCatSummariesByIDs :many
select c.id, c.name, coalesce(c.photo_url, m.url, '') as photo_url
from cats c
left join media m on m.id = c.primary_photo_id
where c.id = any($1::uuid[])
`

type GetCatSummariesByIDsRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     pgtype.Text `json:"name"`
	PhotoUrl string      `json:"photo_url"`
}

// batch display lookup (name + resolved primary photo) for exactly the cat
// ids the profile's recent-contributions list is about to render — never
// the caller's full contribution history, which can be much larger. Mirrors
// ListCatsInBounds' coalesce(photo_url, media.url) resolution so a seeded
// and a created cat both surface the same primary_photo field.
func (q *Queries) GetCatSummariesByIDs(ctx context.Context, ids []pgtype.UUID) ([]GetCatSummariesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCatSummariesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCatSummariesByIDsRow
	for rows.Next() {
		var i GetCatSummariesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PhotoUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCreatedCatsForBadges = `-- name: ListUserCreatedCatsForBadges :many
select id as cat_id, created_at
from cats
where created_by_user_id = $1
order by created_at asc
`

type ListUserCreatedCatsForBadgesRow struct {
	CatID     pgtype.UUID        `json:"cat_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// a created cat counts toward cats_of_istanbul the same way a media/update
// contribution does (docs/product/badges.md's cats_of_istanbul condition).
func (q *Queries) ListUserCreatedCatsForBadges(ctx context.Context, createdByUserID pgtype.UUID) ([]ListUserCreatedCatsForBadgesRow, error) {
	rows, err := q.db.Query(ctx, listUserCreatedCatsForBadges, createdByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCreatedCatsForBadgesRow
	for rows.Next() {
		var i ListUserCreatedCatsForBadgesRow
		if err := rows.Scan(&i.CatID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNeedsHelpUpdatesForBadges = `-- name: ListUserNeedsHelpUpdatesForBadges :many
select cat_id, created_at, seq, needs_help_category
from updates
where author_user_id = $1 and kind = 'needs_help' and deleted_at is null
order by created_at asc, seq asc
`

type ListUserNeedsHelpUpdatesForBadgesRow struct {
	CatID             pgtype.UUID        `json:"cat_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Seq               pgtype.Int8        `json:"seq"`
	NeedsHelpCategory pgtype.Text        `json:"needs_help_category"`
}

// a needs-help report counts toward cats_of_istanbul's "contribute via
// updates, media, or cat creation" condition and the profile's total
// contribution/help counts, but never toward the status-based badges
// (first_sighting/feeder/water_helper/neighborhood_watcher), which only
// look at ordinary-update statuses. Post-#101 this lists only the legacy
// pre-migration subtype rows (kind = 'needs_help') — a new help mark is a
// kind = 'ordinary' row and comes through ListUserOrdinaryUpdatesForBadges
// with its needs_help flag, so no row is ever counted twice.
// needs_help_category is carried along purely for the profile's
// recent-contributions display, not for badge derivation. Legacy rows
// predate deletability, but the deleted_at filter keeps this list's
// contract aligned with the ordinary one's.
func (q *Queries) ListUserNeedsHelpUpdatesForBadges(ctx context.Context, authorUserID pgtype.UUID) ([]ListUserNeedsHelpUpdatesForBadgesRow, error) {
	rows, err := q.db.Query(ctx, listUserNeedsHelpUpdatesForBadges, authorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserNeedsHelpUpdatesForBadgesRow
	for rows.Next() {
		var i ListUserNeedsHelpUpdatesForBadgesRow
		if err := rows.Scan(
			&i.CatID,
			&i.CreatedAt,
			&i.Seq,
			&i.NeedsHelpCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrdinaryUpdatesForBadges = `-- name: ListUserOrdinaryUpdatesForBadges :many
select
  u.cat_id,
  u.created_at,
  u.seq,
  u.needs_help,
  u.needs_help_category,
  coalesce(array_agg(s.status order by s.status) filter (where s.status is not null), '{}')::text[] as statuses
from updates u
left join update_statuses s on s.update_id = u.id
where u.author_user_id = $1
  and u.kind = 'ordinary'
  and u.deleted_at is null
group by u.id
order by u.created_at asc, u.seq asc
`

type ListUserOrdinaryUpdatesForBadgesRow struct {
	CatID             pgtype.UUID        `json:"cat_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Seq               pgtype.Int8        `json:"seq"`
	NeedsHelp         bool               `json:"needs_help"`
	NeedsHelpCategory pgtype.Text        `json:"needs_help_category"`
	Statuses          []string           `json:"statuses"`
}

// issue #80: one row per ordinary update the account authored, oldest
// first, with its full status set — feeds ProfileService.BadgeProgress's
// oldest-to-newest threshold walk (mirrors the approved prototype's
// badgeProgress in prototype/data.js). Soft-deleted updates (see migration
// 00020) are excluded: a corrected-away update never counts toward a
// threshold. Legacy needs-help subtype rows (kind = 'needs_help') are
// listed separately (see ListUserNeedsHelpUpdatesForBadges); a post-#101
// help mark is a kind = 'ordinary' row and appears here, with its
// needs_help flag and any compat-recorded category carried along for the
// profile's help count and recent-contributions display.
func (q *Queries) ListUserOrdinaryUpdatesForBadges(ctx context.Context, authorUserID pgtype.UUID) ([]ListUserOrdinaryUpdatesForBadgesRow, error) {
	rows, err := q.db.Query(ctx, listUserOrdinaryUpdatesForBadges, authorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserOrdinaryUpdatesForBadgesRow
	for rows.Next() {
		var i ListUserOrdinaryUpdatesForBadgesRow
		if err := rows.Scan(
			&i.CatID,
			&i.CreatedAt,
			&i.Seq,
			&i.NeedsHelp,
			&i.NeedsHelpCategory,
			&i.Statuses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
