// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// lets the updates-history endpoint 404 on an unknown cat instead of
	// silently returning an empty page indistinguishable from "no history yet".
	CatExists(ctx context.Context, id pgtype.UUID) (bool, error)
	// atomic compare-and-set (code review fix, issue #58): the previous
	// read-then-unconditional-update let two concurrent verifications of the
	// same code both pass validation in application code before either wrote
	// consumed_at, so both could proceed to account linking and session
	// issuance. this single statement re-evaluates every validity predicate
	// (still the phone's latest code, unconsumed, unexpired, attempts
	// remaining) atomically against the row's current committed state; a
	// concurrent loser's update commits after the winner's and matches zero
	// rows, since consumed_at is no longer null by the time it runs. the
	// "still the latest" subquery preserves the existing "only the most
	// recently issued code is ever checked" behavior — a race can't smuggle in
	// consumption of a superseded code.
	ConsumeOtpCodeIfValid(ctx context.Context, arg ConsumeOtpCodeIfValidParams) (pgtype.UUID, error)
	// no endpoint sets this yet — trait selection is out of scope for issue #21
	// and belongs to the future add/edit-cat flow. used by seed data only.
	CreateCatTrait(ctx context.Context, arg CreateCatTraitParams) error
	// stores a new device row; only the sha-256 hash of the raw token is
	// persisted here — the raw token is returned to the caller once and
	// never stored (see docs/architecture/db.md). push_token is optional.
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (CreateDeviceRow, error)
	// idempotent by construction: on conflict do nothing means a repeat follow
	// for the same (device_id, cat_id) pair — including two concurrent
	// duplicate requests — leaves exactly one row, never an error or a
	// duplicate (issue #44).
	CreateFollow(ctx context.Context, arg CreateFollowParams) error
	// issue #38: explicit enqueue replaces the removed updates_enqueue_outbox
	// trigger (migration 00009) — Store.CreateOrdinaryUpdate is now the only
	// caller, inside the same transaction as the update/statuses/last_update_at
	// writes, so only an authenticated ordinary write ever produces outbox
	// work. notification_outbox.update_id is unique, so retrying or repeating
	// an enqueue for the same update fails loudly (and rolls the whole
	// transaction back) instead of duplicating work.
	CreateNotificationOutbox(ctx context.Context, arg CreateNotificationOutboxParams) error
	CreateOtpCode(ctx context.Context, arg CreateOtpCodeParams) (CreateOtpCodeRow, error)
	// only the hash is ever persisted; the raw token is returned to the
	// caller once and never stored (mirrors CreateDevice's convention).
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	// kind discriminates an ordinary status update from a needs-help one (issue
	// #23); needs_help_category/needs_help_expires_at are null for an ordinary
	// update and required for a needs-help one — enforced by
	// updates_kind_fields_ck, not application code alone. created_at stays
	// caller-supplied (not now()) so seed data and tests can construct
	// deterministic, repeatable timelines and exact expiry-boundary scenarios;
	// needs_help_expires_at is likewise caller-supplied here (computed as
	// created_at + 72h at the call site, per the fixed mvp expiry) rather than
	// in sql, for the same determinism reason. upserts on id (like UpsertCat) so
	// re-running the seed script with fixed ids stays idempotent instead of
	// erroring on a duplicate key; seq is never touched by the update branch,
	// so a row's tie-breaker position is stable. author_device_id is nullable
	// (see 00008) — set only by the write path introduced in issue #36, from
	// authenticated device context, never client-supplied; seed/needs-help rows
	// leave it null.
	CreateUpdate(ctx context.Context, arg CreateUpdateParams) (CreateUpdateRow, error)
	CreateUpdateStatus(ctx context.Context, arg CreateUpdateStatusParams) error
	// creates a new account for a normalized phone number. the unique
	// constraint on users.phone is what makes concurrent otp verification for
	// the same number resolve to exactly one account: the losing concurrent
	// insert fails with a unique violation and the caller falls back to
	// GetUserByPhone (issue #58). display_name is null at creation — set
	// afterwards via UpdateUserDisplayName once the new-account minimum-profile
	// step collects it.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// idempotent: unfollowing a cat this device doesn't currently follow
	// deletes zero rows and succeeds silently rather than erroring (issue #44).
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	// traits are fetched separately via ListCatTraits (join against the traits
	// vocabulary) rather than aggregated in here, so each trait can carry its
	// display_name without hand-rolling composite-type aggregation in sql. the
	// lateral join is the same latest-needs-help-update lookup as
	// ListCatsInBounds, unfiltered by expiry for the same reason.
	GetCatByID(ctx context.Context, id pgtype.UUID) (GetCatByIDRow, error)
	// issue #58: read a device's current account link before deciding whether
	// otp verification may link it (see LinkDeviceToUser).
	GetDeviceByID(ctx context.Context, id pgtype.UUID) (GetDeviceByIDRow, error)
	// resolves an inbound X-Device-Token to its non-secret device_id and, if
	// the device has been linked to an account (issue #58), that account's id.
	// the middleware calls this after hashing the presented token; only
	// the non-secret fields are returned — the hash is never echoed back.
	GetDeviceByTokenHash(ctx context.Context, tokenHash string) (GetDeviceByTokenHashRow, error)
	// the most recently issued code for a phone number, regardless of whether
	// it's already consumed or expired — the service layer decides validity
	// against its own injected clock so behavior stays deterministically
	// testable (issue #58).
	GetLatestOtpCode(ctx context.Context, phone string) (OtpCode, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	IncrementOtpAttempts(ctx context.Context, id pgtype.UUID) error
	// issue #58: idempotent by construction — setting user_id to the same
	// value on a retry (or on a device already linked to this exact account)
	// is a no-op update. the service layer rejects linking a device already
	// linked to a *different* account before this query ever runs; a device is
	// linked to at most one account, ever (see docs/architecture/db.md).
	LinkDeviceToUser(ctx context.Context, arg LinkDeviceToUserParams) error
	// the selectable vocabulary: what the future grouped multi-select picker
	// (product-owner decision on issue #21/#23) renders as options, ordered
	// group-then-trait so a client can render section headers without its own
	// sort pass. retired (active=false) traits are excluded here but not from
	// ListCatTraits, so a cat that already carries a retired trait keeps
	// showing it. a trait with no group (group_key null) sorts after every
	// grouped trait rather than interleaving arbitrarily.
	ListActiveTraits(ctx context.Context) ([]ListActiveTraitsRow, error)
	// joins the vocabulary (and its group) so cat detail can render a display
	// label without a separate vocabulary fetch. intentionally not filtered by
	// traits.active: retiring a trait must not erase a cat's existing,
	// historical association.
	ListCatTraits(ctx context.Context, catID pgtype.UUID) ([]ListCatTraitsRow, error)
	// newest-first keyset pagination: (created_at, seq) both descending, seq
	// breaking ties deterministically when created_at collides. before_created_at
	// is null on the first page; the caller fetches row_limit+1 rows to detect
	// whether a next page exists, then trims the extra row before responding.
	// kind/needs_help_category/needs_help_expires_at (issue #23) let the client
	// render a needs-help entry distinctly from an ordinary one; active-vs-
	// expired for a needs-help entry is decided by the service layer against an
	// injected clock, never by this query's own now() or the client's own clock.
	ListCatUpdates(ctx context.Context, arg ListCatUpdatesParams) ([]ListCatUpdatesRow, error)
	// area && envelope::geography uses cats_area_gix (gist on geography supports
	// the && bounding-box operator); st_makeenvelope builds the requested viewport.
	// name/area_label are the minimum extra fields the map-marker preview sheet
	// needs (issue #21 prototype-parity correction) — no second full-detail
	// fetch on marker tap. the lateral join returns each cat's latest
	// needs-help update (issue #4/#23), whether or not it has since expired —
	// ListNearby (service layer) is the one that decides active-vs-expired,
	// against an injected clock, not this query's own now().
	ListCatsInBounds(ctx context.Context, arg ListCatsInBoundsParams) ([]ListCatsInBoundsRow, error)
	// issue #44: a device's followed cats, ordered by most recent cat activity.
	// last_update_at desc nulls last puts a cat that has never had an update
	// after every cat that has, however old — no activity is never "fresher"
	// than old activity. c.id desc is the deterministic tie-breaker for equal
	// last_update_at, including the shared-null case, since last_update_at
	// alone can't order two never-updated cats against each other. joins cats
	// (not just follows) so the response carries the same cat-summary shape as
	// the map/detail endpoints, including each cat's latest needs-help update
	// via the same unfiltered-by-expiry lateral join as ListCatsInBounds/
	// GetCatByID — the service layer decides active-vs-expired against its own
	// injected clock, never this query's own now().
	ListFollowedCats(ctx context.Context, deviceID pgtype.UUID) ([]ListFollowedCatsRow, error)
	ListWorkspacePings(ctx context.Context) ([]ListWorkspacePingsRow, error)
	// idempotent, unconditional revoke — used only by logout, where "already
	// revoked/expired" is not an error (see SessionService.Revoke). Never used
	// for rotation; see RevokeRefreshTokenIfActive for that.
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	// atomic conditional revoke (code review fix, issue #58): the previous
	// read-then-unconditional-revoke let two concurrent refresh calls
	// presenting the same token both pass validation before either revoked
	// it, so both could mint a replacement session from one token. this
	// statement re-evaluates "unrevoked and unexpired" atomically against the
	// row's current committed state; a concurrent loser's update commits
	// after the winner's and matches zero rows, since revoked_at is no longer
	// null by then.
	RevokeRefreshTokenIfActive(ctx context.Context, arg RevokeRefreshTokenIfActiveParams) (pgtype.UUID, error)
	// issue #36: run inside the same transaction as CreateUpdate/CreateUpdateStatus
	// so a new ordinary update and the cat's last_update_at commit atomically.
	// issue #38: monotonic — greatest() already ignores a null argument
	// (postgres greatest/least ignore nulls, returning null only when every
	// argument is null), so a cat's first-ever update still sets last_update_at
	// correctly. this keeps an out-of-order commit (an older update committing
	// after a newer one) from moving a cat's displayed freshness backwards.
	UpdateCatLastUpdateAt(ctx context.Context, arg UpdateCatLastUpdateAtParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpsertCat(ctx context.Context, arg UpsertCatParams) (pgtype.UUID, error)
	// loads/updates the vocabulary itself (seed data only for now — there's no
	// admin endpoint). upserting on key lets seed re-runs adjust display_name/
	// group_key/sort_order/active in place instead of erroring on a duplicate key.
	UpsertTrait(ctx context.Context, arg UpsertTraitParams) (string, error)
	// loads/updates the group vocabulary (seed data only, same rationale as
	// UpsertTrait).
	UpsertTraitGroup(ctx context.Context, arg UpsertTraitGroupParams) (string, error)
	UpsertWorkspacePing(ctx context.Context, arg UpsertWorkspacePingParams) (UpsertWorkspacePingRow, error)
}

var _ Querier = (*Queries)(nil)
