// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
insert into refresh_tokens (id, user_id, token_hash, expires_at)
values ($1, $2, $3, $4)
returning id, created_at
`

type CreateRefreshTokenParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateRefreshTokenRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// only the hash is ever persisted; the raw token is returned to the
// caller once and never stored (mirrors CreateDevice's convention).
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
select id, user_id, token_hash, expires_at, revoked_at, created_at
from refresh_tokens
where token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
update refresh_tokens set revoked_at = $1 where id = $2
`

type RevokeRefreshTokenParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        pgtype.UUID        `json:"id"`
}

// idempotent, unconditional revoke — used only by logout, where "already
// revoked/expired" is not an error (see SessionService.Revoke). Never used
// for rotation; see RevokeRefreshTokenIfActive for that.
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.RevokedAt, arg.ID)
	return err
}

const revokeRefreshTokenIfActive = `-- name: RevokeRefreshTokenIfActive :one
update refresh_tokens
set revoked_at = $1
where id = $2
  and revoked_at is null
  and expires_at > $3
returning user_id
`

type RevokeRefreshTokenIfActiveParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        pgtype.UUID        `json:"id"`
	Now       pgtype.Timestamptz `json:"now"`
}

// atomic conditional revoke (code review fix, issue #58): the previous
// read-then-unconditional-revoke let two concurrent refresh calls
// presenting the same token both pass validation before either revoked
// it, so both could mint a replacement session from one token. this
// statement re-evaluates "unrevoked and unexpired" atomically against the
// row's current committed state; a concurrent loser's update commits
// after the winner's and matches zero rows, since revoked_at is no longer
// null by then.
func (q *Queries) RevokeRefreshTokenIfActive(ctx context.Context, arg RevokeRefreshTokenIfActiveParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, revokeRefreshTokenIfActive, arg.RevokedAt, arg.ID, arg.Now)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
