// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
insert into reports (id, reporter_user_id, target_type, target_id, reason, note)
values ($1, $2, $3, $4, $5, $6)
on conflict (reporter_user_id, target_type, target_id) where status = 'open' do nothing
returning id, reporter_user_id, target_type, target_id, reason, note, status, created_at, resolved_at
`

type CreateReportParams struct {
	ID             pgtype.UUID `json:"id"`
	ReporterUserID pgtype.UUID `json:"reporter_user_id"`
	TargetType     string      `json:"target_type"`
	TargetID       pgtype.UUID `json:"target_id"`
	Reason         string      `json:"reason"`
	Note           pgtype.Text `json:"note"`
}

// issue #233: reporter_user_id/target_type/target_id/reason are all
// validated by the service layer before this runs (target existence,
// closed reason vocabulary, other-requires-note). idempotent by
// construction, mirroring CreateMedia/CreateCat's own idempotency-key
// pattern: on conflict do nothing on the partial (reporter_user_id,
// target_type, target_id) where status = 'open' unique index means a
// retried/duplicate report never creates a second active row — no row
// comes back (pgx.ErrNoRows) on the conflicting retry, and the caller
// (ReportsService) looks the existing open report up via
// GetOpenReportByReporterAndTarget instead.
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ReporterUserID,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.Note,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getOpenReportByReporterAndTarget = `-- name: GetOpenReportByReporterAndTarget :one
select id, reporter_user_id, target_type, target_id, reason, note, status, created_at, resolved_at from reports
where reporter_user_id = $1
  and target_type = $2
  and target_id = $3
  and status = 'open'
`

type GetOpenReportByReporterAndTargetParams struct {
	ReporterUserID pgtype.UUID `json:"reporter_user_id"`
	TargetType     string      `json:"target_type"`
	TargetID       pgtype.UUID `json:"target_id"`
}

// resolves a retried/duplicate POST /v1/reports (same reporter, same
// target, still open) to the report it already created — mirrors
// GetCatByIdempotencyKey/GetMediaByIdempotencyKey's own conflict-recovery
// shape.
func (q *Queries) GetOpenReportByReporterAndTarget(ctx context.Context, arg GetOpenReportByReporterAndTargetParams) (Report, error) {
	row := q.db.QueryRow(ctx, getOpenReportByReporterAndTarget, arg.ReporterUserID, arg.TargetType, arg.TargetID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
