// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traits.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCatTrait = `-- name: CreateCatTrait :exec
insert into cat_traits (cat_id, trait_key)
values ($1, $2)
on conflict (cat_id, trait_key) do nothing
`

type CreateCatTraitParams struct {
	CatID    pgtype.UUID `json:"cat_id"`
	TraitKey string      `json:"trait_key"`
}

// no endpoint sets this yet — trait selection is out of scope for issue #21
// and belongs to the future add/edit-cat flow. used by seed data only.
func (q *Queries) CreateCatTrait(ctx context.Context, arg CreateCatTraitParams) error {
	_, err := q.db.Exec(ctx, createCatTrait, arg.CatID, arg.TraitKey)
	return err
}

const listActiveTraits = `-- name: ListActiveTraits :many
select key, display_name
from traits
where active
order by sort_order, key
`

type ListActiveTraitsRow struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
}

// the selectable vocabulary: what a future add/edit-cat flow renders as
// options. retired (active=false) traits are excluded here but not from
// ListCatTraits, so a cat that already carries a retired trait keeps
// showing it.
func (q *Queries) ListActiveTraits(ctx context.Context) ([]ListActiveTraitsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTraits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTraitsRow
	for rows.Next() {
		var i ListActiveTraitsRow
		if err := rows.Scan(&i.Key, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatTraits = `-- name: ListCatTraits :many
select t.key, t.display_name
from cat_traits ct
join traits t on t.key = ct.trait_key
where ct.cat_id = $1
order by t.sort_order, t.key
`

type ListCatTraitsRow struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
}

// joins the vocabulary so cat detail can render a display label without a
// separate vocabulary fetch. intentionally not filtered by traits.active:
// retiring a trait must not erase a cat's existing, historical association.
func (q *Queries) ListCatTraits(ctx context.Context, catID pgtype.UUID) ([]ListCatTraitsRow, error) {
	rows, err := q.db.Query(ctx, listCatTraits, catID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatTraitsRow
	for rows.Next() {
		var i ListCatTraitsRow
		if err := rows.Scan(&i.Key, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrait = `-- name: UpsertTrait :one
insert into traits (key, display_name, active, sort_order)
values ($1, $2, $3, $4)
on conflict (key) do update set
  display_name = excluded.display_name,
  active = excluded.active,
  sort_order = excluded.sort_order
returning key
`

type UpsertTraitParams struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	Active      bool   `json:"active"`
	SortOrder   int32  `json:"sort_order"`
}

// loads/updates the vocabulary itself (seed data only for now — there's no
// admin endpoint). upserting on key lets seed re-runs adjust display_name/
// sort_order/active in place instead of erroring on a duplicate key.
func (q *Queries) UpsertTrait(ctx context.Context, arg UpsertTraitParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertTrait,
		arg.Key,
		arg.DisplayName,
		arg.Active,
		arg.SortOrder,
	)
	var key string
	err := row.Scan(&key)
	return key, err
}
