// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updates.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUpdate = `-- name: CreateUpdate :one
insert into updates (id, cat_id, comment, created_at)
values ($1, $2, $3, $4)
on conflict (id) do update set
  comment = excluded.comment,
  created_at = excluded.created_at
returning id, seq
`

type CreateUpdateParams struct {
	ID        pgtype.UUID        `json:"id"`
	CatID     pgtype.UUID        `json:"cat_id"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CreateUpdateRow struct {
	ID  pgtype.UUID `json:"id"`
	Seq pgtype.Int8 `json:"seq"`
}

// created_at is caller-supplied (not now()) so seed data and tests can
// construct deterministic, repeatable timelines and tie-breaker scenarios.
// upserts on id (like UpsertCat) so re-running the seed script with fixed
// ids stays idempotent instead of erroring on a duplicate key; seq is never
// touched by the update branch, so a row's tie-breaker position is stable.
func (q *Queries) CreateUpdate(ctx context.Context, arg CreateUpdateParams) (CreateUpdateRow, error) {
	row := q.db.QueryRow(ctx, createUpdate,
		arg.ID,
		arg.CatID,
		arg.Comment,
		arg.CreatedAt,
	)
	var i CreateUpdateRow
	err := row.Scan(&i.ID, &i.Seq)
	return i, err
}

const createUpdateStatus = `-- name: CreateUpdateStatus :exec
insert into update_statuses (update_id, status)
values ($1, $2)
on conflict (update_id, status) do nothing
`

type CreateUpdateStatusParams struct {
	UpdateID pgtype.UUID `json:"update_id"`
	Status   string      `json:"status"`
}

func (q *Queries) CreateUpdateStatus(ctx context.Context, arg CreateUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, createUpdateStatus, arg.UpdateID, arg.Status)
	return err
}

const listCatUpdates = `-- name: ListCatUpdates :many
select
  u.id,
  u.comment,
  u.created_at,
  u.seq,
  coalesce(array_agg(s.status order by s.status) filter (where s.status is not null), '{}')::text[] as statuses
from updates u
left join update_statuses s on s.update_id = u.id
where u.cat_id = $1
  and (
    $2::timestamptz is null
    or u.created_at < $2::timestamptz
    or (u.created_at = $2::timestamptz and u.seq < $3::bigint)
  )
group by u.id
order by u.created_at desc, u.seq desc
limit $4::int
`

type ListCatUpdatesParams struct {
	CatID           pgtype.UUID        `json:"cat_id"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeSeq       pgtype.Int8        `json:"before_seq"`
	RowLimit        int32              `json:"row_limit"`
}

type ListCatUpdatesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Seq       pgtype.Int8        `json:"seq"`
	Statuses  []string           `json:"statuses"`
}

// newest-first keyset pagination: (created_at, seq) both descending, seq
// breaking ties deterministically when created_at collides. before_created_at
// is null on the first page; the caller fetches row_limit+1 rows to detect
// whether a next page exists, then trims the extra row before responding.
func (q *Queries) ListCatUpdates(ctx context.Context, arg ListCatUpdatesParams) ([]ListCatUpdatesRow, error) {
	rows, err := q.db.Query(ctx, listCatUpdates,
		arg.CatID,
		arg.BeforeCreatedAt,
		arg.BeforeSeq,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatUpdatesRow
	for rows.Next() {
		var i ListCatUpdatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Comment,
			&i.CreatedAt,
			&i.Seq,
			&i.Statuses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
