// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updates.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUpdate = `-- name: CreateUpdate :one
insert into updates (id, cat_id, kind, comment, created_at, needs_help_category, needs_help_expires_at)
values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
on conflict (id) do update set
  kind = excluded.kind,
  comment = excluded.comment,
  created_at = excluded.created_at,
  needs_help_category = excluded.needs_help_category,
  needs_help_expires_at = excluded.needs_help_expires_at
returning id, seq
`

type CreateUpdateParams struct {
	ID                 pgtype.UUID        `json:"id"`
	CatID              pgtype.UUID        `json:"cat_id"`
	Kind               string             `json:"kind"`
	Comment            pgtype.Text        `json:"comment"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	NeedsHelpCategory  pgtype.Text        `json:"needs_help_category"`
	NeedsHelpExpiresAt pgtype.Timestamptz `json:"needs_help_expires_at"`
}

type CreateUpdateRow struct {
	ID  pgtype.UUID `json:"id"`
	Seq pgtype.Int8 `json:"seq"`
}

// kind discriminates an ordinary status update from a needs-help one (issue
// #23); needs_help_category/needs_help_expires_at are null for an ordinary
// update and required for a needs-help one — enforced by
// updates_kind_fields_ck, not application code alone. created_at stays
// caller-supplied (not now()) so seed data and tests can construct
// deterministic, repeatable timelines and exact expiry-boundary scenarios;
// needs_help_expires_at is likewise caller-supplied here (computed as
// created_at + 72h at the call site, per the fixed mvp expiry) rather than
// in sql, for the same determinism reason. upserts on id (like UpsertCat) so
// re-running the seed script with fixed ids stays idempotent instead of
// erroring on a duplicate key; seq is never touched by the update branch,
// so a row's tie-breaker position is stable.
func (q *Queries) CreateUpdate(ctx context.Context, arg CreateUpdateParams) (CreateUpdateRow, error) {
	row := q.db.QueryRow(ctx, createUpdate,
		arg.ID,
		arg.CatID,
		arg.Kind,
		arg.Comment,
		arg.CreatedAt,
		arg.NeedsHelpCategory,
		arg.NeedsHelpExpiresAt,
	)
	var i CreateUpdateRow
	err := row.Scan(&i.ID, &i.Seq)
	return i, err
}

const createUpdateStatus = `-- name: CreateUpdateStatus :exec
insert into update_statuses (update_id, status)
values ($1, $2)
on conflict (update_id, status) do nothing
`

type CreateUpdateStatusParams struct {
	UpdateID pgtype.UUID `json:"update_id"`
	Status   string      `json:"status"`
}

func (q *Queries) CreateUpdateStatus(ctx context.Context, arg CreateUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, createUpdateStatus, arg.UpdateID, arg.Status)
	return err
}

const listCatUpdates = `-- name: ListCatUpdates :many
select
  u.id,
  u.kind,
  u.comment,
  u.created_at,
  u.seq,
  u.needs_help_category,
  u.needs_help_expires_at,
  coalesce(array_agg(s.status order by s.status) filter (where s.status is not null), '{}')::text[] as statuses
from updates u
left join update_statuses s on s.update_id = u.id
where u.cat_id = $1
  and (
    $2::timestamptz is null
    or u.created_at < $2::timestamptz
    or (u.created_at = $2::timestamptz and u.seq < $3::bigint)
  )
group by u.id
order by u.created_at desc, u.seq desc
limit $4::int
`

type ListCatUpdatesParams struct {
	CatID           pgtype.UUID        `json:"cat_id"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeSeq       pgtype.Int8        `json:"before_seq"`
	RowLimit        int32              `json:"row_limit"`
}

type ListCatUpdatesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Kind               string             `json:"kind"`
	Comment            pgtype.Text        `json:"comment"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Seq                pgtype.Int8        `json:"seq"`
	NeedsHelpCategory  pgtype.Text        `json:"needs_help_category"`
	NeedsHelpExpiresAt pgtype.Timestamptz `json:"needs_help_expires_at"`
	Statuses           []string           `json:"statuses"`
}

// newest-first keyset pagination: (created_at, seq) both descending, seq
// breaking ties deterministically when created_at collides. before_created_at
// is null on the first page; the caller fetches row_limit+1 rows to detect
// whether a next page exists, then trims the extra row before responding.
// kind/needs_help_category/needs_help_expires_at (issue #23) let the client
// render a needs-help entry distinctly from an ordinary one; active-vs-
// expired for a needs-help entry is decided by the service layer against an
// injected clock, never by this query's own now() or the client's own clock.
func (q *Queries) ListCatUpdates(ctx context.Context, arg ListCatUpdatesParams) ([]ListCatUpdatesRow, error) {
	rows, err := q.db.Query(ctx, listCatUpdates,
		arg.CatID,
		arg.BeforeCreatedAt,
		arg.BeforeSeq,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatUpdatesRow
	for rows.Next() {
		var i ListCatUpdatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Comment,
			&i.CreatedAt,
			&i.Seq,
			&i.NeedsHelpCategory,
			&i.NeedsHelpExpiresAt,
			&i.Statuses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
