// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_blocks.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlock = `-- name: CreateBlock :exec
insert into user_blocks (blocker_user_id, blocked_user_id)
values ($1, $2)
on conflict (blocker_user_id, blocked_user_id) do nothing
`

type CreateBlockParams struct {
	BlockerUserID pgtype.UUID `json:"blocker_user_id"`
	BlockedUserID pgtype.UUID `json:"blocked_user_id"`
}

// issue #234: idempotent by construction — re-blocking an account the
// caller already blocks is a no-op that still reports success, the same
// shape CreateFollow uses. blocker_user_id always comes from the
// authenticated session, never from the request body; the self-block case
// is rejected in the service before it reaches the check constraint, so
// the constraint is the backstop, not the error message.
func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock, arg.BlockerUserID, arg.BlockedUserID)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
delete from user_blocks
where blocker_user_id = $1
  and blocked_user_id = $2
`

type DeleteBlockParams struct {
	BlockerUserID pgtype.UUID `json:"blocker_user_id"`
	BlockedUserID pgtype.UUID `json:"blocked_user_id"`
}

// unblocking is a hard delete (the follows lifecycle, not reports'
// open/resolved one): a block carries no state worth keeping once it is
// lifted. deleting a row that isn't there is not an error — unblock is
// idempotent for the same reason block is.
func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.BlockerUserID, arg.BlockedUserID)
	return err
}

const listBlockedAccounts = `-- name: ListBlockedAccounts :many
select b.blocked_user_id, u.display_name, b.created_at
from user_blocks b
join users u on u.id = b.blocked_user_id
where b.blocker_user_id = $1
order by b.created_at desc
`

type ListBlockedAccountsRow struct {
	BlockedUserID pgtype.UUID        `json:"blocked_user_id"`
	DisplayName   pgtype.Text        `json:"display_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// the caller's own block list, joined to users for the display name the
// unblock screen shows. blocks are never public: this is the only read
// that returns them and it is always scoped to the authenticated caller.
func (q *Queries) ListBlockedAccounts(ctx context.Context, blockerUserID pgtype.UUID) ([]ListBlockedAccountsRow, error) {
	rows, err := q.db.Query(ctx, listBlockedAccounts, blockerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedAccountsRow
	for rows.Next() {
		var i ListBlockedAccountsRow
		if err := rows.Scan(&i.BlockedUserID, &i.DisplayName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
