// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (id, phone, phone_verified_at)
values ($1, $2, $3)
returning id, phone, phone_verified_at, created_at, display_name
`

type CreateUserParams struct {
	ID              pgtype.UUID        `json:"id"`
	Phone           string             `json:"phone"`
	PhoneVerifiedAt pgtype.Timestamptz `json:"phone_verified_at"`
}

// creates a new account for a normalized phone number. the unique
// constraint on users.phone is what makes concurrent otp verification for
// the same number resolve to exactly one account: the losing concurrent
// insert fails with a unique violation and the caller falls back to
// GetUserByPhone (issue #58). display_name is null at creation — set
// afterwards via UpdateUserDisplayName once the new-account minimum-profile
// step collects it.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Phone, arg.PhoneVerifiedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.CreatedAt,
		&i.DisplayName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, phone, phone_verified_at, created_at, display_name
from users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.CreatedAt,
		&i.DisplayName,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
select id, phone, phone_verified_at, created_at, display_name
from users
where phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.CreatedAt,
		&i.DisplayName,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
update users set display_name = $1 where id = $2
`

type UpdateUserDisplayNameParams struct {
	DisplayName pgtype.Text `json:"display_name"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateUserDisplayName, arg.DisplayName, arg.ID)
	return err
}
