// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_pings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWorkspacePings = `-- name: ListWorkspacePings :many
select id, message, st_x(location::geometry)::float8 as lng, st_y(location::geometry)::float8 as lat, created_at
from workspace_pings
order by created_at desc
`

type ListWorkspacePingsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Message   string             `json:"message"`
	Lng       float64            `json:"lng"`
	Lat       float64            `json:"lat"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWorkspacePings(ctx context.Context) ([]ListWorkspacePingsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacePings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacePingsRow
	for rows.Next() {
		var i ListWorkspacePingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.Lng,
			&i.Lat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspacePing = `-- name: UpsertWorkspacePing :one
insert into workspace_pings (id, message, location)
values ($1, $2, st_setsrid(st_makepoint($3::float8, $4::float8), 4326))
on conflict (id) do update set message = excluded.message, location = excluded.location
returning id, message, st_x(location::geometry)::float8 as lng, st_y(location::geometry)::float8 as lat, created_at
`

type UpsertWorkspacePingParams struct {
	ID      pgtype.UUID `json:"id"`
	Message string      `json:"message"`
	Lng     float64     `json:"lng"`
	Lat     float64     `json:"lat"`
}

type UpsertWorkspacePingRow struct {
	ID        pgtype.UUID        `json:"id"`
	Message   string             `json:"message"`
	Lng       float64            `json:"lng"`
	Lat       float64            `json:"lat"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertWorkspacePing(ctx context.Context, arg UpsertWorkspacePingParams) (UpsertWorkspacePingRow, error) {
	row := q.db.QueryRow(ctx, upsertWorkspacePing,
		arg.ID,
		arg.Message,
		arg.Lng,
		arg.Lat,
	)
	var i UpsertWorkspacePingRow
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.Lng,
		&i.Lat,
		&i.CreatedAt,
	)
	return i, err
}
